id: FEAT-0252
title: WebGPU Backend (wgpu-native)
owner: ai
status: planned
created: "2025-09-13T00:00:00Z"
priority: critical

description: >
  Implement a WebGPU backend using wgpu-native (preferred) targeting desktop, with optional
  Dawn (C++ WebGPU) support. Ensure API parity with the WebGPU-shaped RHI frontend.
  Use GLFW + webgpu.h for surface creation.

acceptance_criteria:
  - "WebGPU backend compiles and runs core scenes"
  - "GL vs WebGPU image diff < epsilon on 10–20 golden scenes"
  - "Pass/encoder/bind group semantics match frontend expectations"
  - "Can capture frames in RenderDoc (native) and Chrome WebGPU (browser)"

must_requirements:
  - TEST.CROSS_PLATFORM
  - TEST.GOLDEN_SSIM
  - PERF.FRAME_BUDGET

plan:
  - id: PR1
    title: "Backend skeleton + device/queue (wgpu-native)"
    status: planned
    files: ["engine/src/rhi/**", "engine/include/glint3d/rhi*.h", "tests/unit/rhi_test.cpp"]
  - id: PR2
    title: "Pipelines, bind groups, and passes (wgpu-native); optional Dawn path"
    status: planned
    files: ["engine/src/rhi/**", "tests/unit/rhi_test.cpp"]
  - id: PR3
    title: "Surface creation (GLFW + webgpu.h) and swap chain"
    status: planned
    files: ["engine/src/rhi/**", "docs/rhi_architecture.md"]

file_whitelist:
  - "engine/src/rhi/**"
  - "engine/include/glint3d/rhi*.h"
  - "tests/unit/rhi_test.cpp"
  - "docs/rhi_architecture.md"

outputs:
  - engine/src/rhi/rhi-wgpu.cpp
  - docs/rhi_architecture.md

dependencies:
  blocked_by: [FEAT-0248, FEAT-0249, FEAT-0250, FEAT-0251]
