id: FEAT-0253
title: RHI Framebuffer Migration (MSAA/Offscreen/Readback)
owner: ai
status: planned
created: "2025-09-13T15:50:00Z"
priority: critical

description: >
  Complete FEAT-0248 requirements by migrating all direct framebuffer operations
  to RHI render targets. This includes MSAA rendering, offscreen PNG export,
  and raytracer texture integration in render_system.cpp.

acceptance_criteria:
  - "No direct glBindFramebuffer calls outside RHI backend"
  - "No glFramebufferTexture*/glFramebufferRenderbuffer calls outside RHI"
  - "MSAA rendering uses RHI multisampled render targets with resolve"
  - "PNG export uses RHI render targets + readback API"
  - "Raytracer integration uses RHI texture handles exclusively"

must_requirements:
  - ARCH.NO_GL_OUTSIDE_RHI
  - API.PUBLIC_HEADERS_PATH
  - TEST.CROSS_PLATFORM

plan:
  - id: PR1
    title: "Extend RHI with MSAA render target support and resolve operations"
    status: planned
    files: ["engine/include/glint3d/rhi.h", "engine/src/rhi/rhi_gl.cpp"]
  - id: PR2
    title: "Migrate MSAA rendering in RenderSystem to RHI render targets"
    status: planned
    files: ["engine/src/render_system.cpp"]
  - id: PR3
    title: "Migrate offscreen rendering and raytracer integration to RHI"
    status: planned
    files: ["engine/src/render_system.cpp", "engine/src/ibl_system.cpp"]

file_whitelist:
  - "engine/src/render_system.cpp"
  - "engine/src/ibl_system.cpp"
  - "engine/include/glint3d/rhi.h"
  - "engine/src/rhi/rhi_gl.cpp"

outputs:
  - Complete RHI render target abstraction
  - GL-free engine core (except RHI backend)

dependencies:
  blocked_by: [FEAT-0248, FEAT-0250]