id: FEAT-0249
title: Uniform System Migration (UBO ring + reflection)
owner: ai
status: planned
created: "2025-09-13T00:00:00Z"
priority: critical

description: >
  Migrate all uniform updates to a UBO ring allocator with reflection-driven offsets.
  Eliminate per-draw glUniform* calls; validate offsets against shader reflection.

acceptance_criteria:
  - "100% uniform migration to UBO ring allocator"
  - "Reflection-validated offsets; runtime asserts on mismatch"
  - "No glUniform* usage outside GL backend"
  - "Golden tests pass with parity vs pre-migration output"
  - "Reflection is derived from compiled SPIR-V via SPIRV-Reflect"

must_requirements:
  - ARCH.NO_GL_OUTSIDE_RHI
  - TEST.GOLDEN_SSIM
  - TEST.CROSS_PLATFORM
  - PERF.FRAME_BUDGET

plan:
  - id: PR1
    title: "Introduce UBO ring + reflection layer in RHI (DXC + SPIRV-Tools/Reflect)"
    status: planned
    files: ["engine/include/glint3d/rhi*.h", "engine/src/rhi/**", "tests/unit/rhi_test.cpp", "docs/rhi_architecture.md", "docs/rhi_guide.md"]
  - id: PR2
    title: "Migrate call sites to ring allocator"
    status: planned
    files: ["engine/src/rhi/**", "tests/unit/rhi_test.cpp"]

file_whitelist:
  - "engine/src/rhi/**"
  - "engine/include/glint3d/rhi*.h"
  - "tests/unit/rhi_test.cpp"
  - "docs/rhi_architecture.md"

outputs:
  - engine/include/glint3d/rhi.h
  - docs/rhi_architecture.md

dependencies:
  blocked_by: [FEAT-0248]
