checks:
  - id: compute_pipeline_symbols
    description: "ComputePipeline and dispatch present"
    includes: ["engine/include/glint3d/rhi*.h", "engine/src/rhi/**"]
    pattern: "ComputePipeline|dispatch|Dispatch"

  - id: storage_buffer_symbols
    description: "Storage buffer descriptors and bindings present"
    includes: ["engine/include/glint3d/rhi*.h", "engine/src/rhi/**"]
    pattern: "StorageBuffer|SSBO|storage"

