checks:
  - id: no_direct_gl_uniforms
    description: "Ensure no glUniform* outside GL backend"
    includes: ["engine/**.cpp", "engine/**.h"]
    excludes: ["engine/src/rhi/**"]
    pattern: "glUniform"

  - id: no_direct_fbo_binds
    description: "Ensure no direct FBO binds at call sites"
    includes: ["engine/**.cpp", "engine/**.h"]
    excludes: ["engine/src/rhi/**"]
    patterns_any: ["glBindFramebuffer", "glFramebufferTexture*", "glFramebufferRenderbuffer"]

  - id: encoder_usage_present
    description: "Basic usage of CommandEncoder/RenderPassEncoder in RenderSystem"
    includes: ["engine/src/render_system.cpp"]
    pattern: "CommandEncoder|RenderPassEncoder"

