id: FEAT-0248
title: RHI API Shape (BindGroups/Encoders/Queues)
owner: ai
status: planned
created: "2025-09-13T00:00:00Z"
priority: critical

description: >
  Finalize the WebGPU-shaped RHI frontend: add PipelineLayout, BindGroupLayout,
  BindGroup, CommandEncoder, RenderPassEncoder, Queue, Fence, and ResourceState.
  Route all GL call sites through encoders/passes; remove direct FBO binds and any glUniform* usage.

acceptance_criteria:
  - "All GL call sites route via CommandEncoder/RenderPassEncoder"
  - "No direct FBO binds at call sites"
  - "No glUniform* usage in engine outside GL backend"
  - "Queue submit/encoder model in place with basic validation"
  - "Docs updated to WebGPU-shaped terminology (bind groups, passes, queues)"

must_requirements:
  - ARCH.NO_GL_OUTSIDE_RHI
  - API.PUBLIC_HEADERS_PATH
  - TEST.CROSS_PLATFORM

plan:
  - id: PR1
    title: "Introduce Pipeline/BindGroup layouts and encoders"
    status: planned
    files: ["engine/include/glint3d/rhi.h", "engine/include/glint3d/rhi_types.h", "engine/src/rhi/**"]
  - id: PR2
    title: "Refactor GL backend to encoders/passes"
    status: planned
    files: ["engine/src/rhi/rhi-gl.cpp", "engine/src/rhi/**"]
  - id: PR3
    title: "Route RenderSystem through CommandEncoder/RenderPassEncoder"
    status: planned
    files: ["engine/src/render_system.cpp", "tests/unit/rhi_test.cpp"]

file_whitelist:
  - "engine/src/rhi/**"
  - "engine/include/glint3d/rhi*.h"
  - "tests/unit/rhi_test.cpp"
  - "docs/rhi_architecture.md"

outputs:
  - engine/include/glint3d/rhi.h
  - docs/rhi_architecture.md

dependencies:
  blocked_by: [FEAT-0242]

